lacart/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import (
    index, product, CheckoutView,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    remove_single_item_from_cart,
    add_single_item_to_cart,
    process_payment,
    payment_done,
    payment_canceled,
    AddCouponView,
    RequestRefundView,
    profile_summary,
    search,
)

app_name = 'shop'

urlpatterns = [
    path('', index, name="item_list"),
    path('category/<slug:tag_slug>/', index, name='item_list_by_category'),
    path('product/<slug>/', product, name="product"),
    path('product/<slug>/add-to-cart/', add_to_cart, name="add-to-cart"),
    path('product/<slug>/remove-from-cart/', remove_from_cart, name="remove-from-cart"),
    path('product/<slug>/remove_single_item_from_cart/', remove_single_item_from_cart, name="remove_single_item_from_cart"),
    path('product/<slug>/add_single_item_to_cart/', add_single_item_to_cart, name="add_single_item_to_cart"),
    path('product/<slug>/remove_single_item_from_cart/', remove_single_item_from_cart, name="remove_single_item_from_cart"),
    path('order_summary/', OrderSummaryView.as_view(), name="order_summary"),
    path('checkout', CheckoutView.as_view(), name="checkout"),
    path('payment/<payment_option>/', process_payment, name="payment"),
    path('payment_done/', payment_done, name="payment_done"),
    path('payment_cancelled/', payment_canceled, name="payment_cancelled"),
    path('add_coupon/', AddCouponView.as_view(), name="add_coupon"),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('profile/', profile_summary, name='profile_summary'),
    path('search/', search, name='search'),
]

shop/models.py
from django.conf import settings
from taggit.managers import TaggableManager
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField


# Create your models here.
LABEL_CHOICES = (
    ('P', 'NEW'),
    ('S', 'SALE'),
    ('D', 'DISCOUNT')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    tags = TaggableManager() # categories
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField(max_length=250)
    description = models.TextField()
    image = models.ImageField()


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:product', args=[
            self.slug
        ])

    def get_add_to_cart_url(self):
        return reverse('shop:add-to-cart', args=[
            self.slug
        ])

    def get_remove_from_cart_url(self):
        return reverse('shop:remove-from-cart', args=[
            self.slug
        ])

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


# class Transaction(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     order_id = models.CharField(max_length=120)
#     ref_code = models.CharField(max_length=20)
#     amount = models.FloatField()
#     success = models.BooleanField(default=True)
#     timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

#     def __str__(self):
#         return self.order_id

#     class Meta:
#         ordering = ['-timestamp']

shop/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = (
    ('M', 'Momo Pay'),
    ('P', 'Paypal')
)

class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(
        attrs={
        'class': 'custom-select d-block w-100'
    }))
    shipping_zip = forms.CharField(required=False)
    same_shipping_address = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    set_default_shipping = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    use_default_shipping = forms.BooleanField(widget=forms.CheckboxInput(), required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(
        attrs={
        'class': 'custom-select d-block w-100'
    }))
    billing_zip = forms.CharField(required=False)
    set_default_billing = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    use_default_billing = forms.BooleanField(widget=forms.CheckboxInput(), required=False)

    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'Promo code'
    }))


class RefundForm(forms.Form):
    email = forms.EmailField()
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))

templates/checkout-page.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

  <!--Main layout-->
  <main class="mt-5">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">


            <!--Card content-->
            <form class="card-body" method="post">


              {% csrf_token %}
              <h3 class="my-2 h3">Shipping Address</h3>
              <!--address-->
              <div class="hide_shipping_form">

                <div class="md-form mb-5">
                  <input type="text" id="id_shipping_address" name="shipping_address" class="form-control" placeholder="1234 Main St">
                  <label for="id_shipping_address" class="">Address</label>
                </div>

                <!--address-2-->
                <div class="md-form mb-5">
                  <input type="text" id="id_shipping_address2" class="form-control" placeholder="Apartment or suite">
                  <label for="id_shipping_address2" name="shipping_address2" class="">Apartment address (optional)</label>
                </div>

                <!--Grid row-->
                <div class="row">

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-12 mb-2">

                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>

                  </div>
                  <!--Grid column-->

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-6 mb-4">

                    <label for="id_shipping_zip">Zip</label>
                    <input type="text" class="form-control" id="id_shipping_zip" name="shipping_zip" placeholder="">
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>

                  </div>
                  <!--Grid column-->

                </div>
                <!--Grid row-->


                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="id_same_shipping_address" name="same_shipping_address">
                  <label class="custom-control-label" for="id_same_shipping_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="id_set_default_shipping" name="set_default_shipping">
                  <label class="custom-control-label" for="id_set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="id_use_default_shipping">
                <label class="custom-control-label" for="id_use_default_shipping" name="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

                <hr class="mb-4">

              <h3 class="my-2 h3">Billing Address</h3>
              <div class="hide_billing_form">
                <!--address-->
                <div class="md-form mb-5">
                  <input type="text" id="id_billing_address" name="billing_address" class="form-control" placeholder="1234 Main St">
                  <label for="id_billing_address" class="">Address</label>
                </div>

                <!--address-2-->
                <div class="md-form mb-5">
                  <input type="text" id="id_billing_address2" class="form-control" placeholder="Apartment or suite">
                  <label for="id_billing_address2" name="billing_address2" class="">Apartment address (optional)</label>
                </div>

                <!--Grid row-->
                <div class="row">

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-12 mb-2">

                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>

                  </div>
                  <!--Grid column-->

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-6 mb-4">

                    <label for="id_billing_zip">Zip</label>
                    <input type="text" class="form-control" id="id_billing_zip" name="billing_zip" placeholder="">
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>

                  </div>
                  <!--Grid column-->

                </div>
                <!--Grid row-->


                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="id_set_default_billing" name="set_default_billing">
                  <label class="custom-control-label" for="id_set_default_billing" >Save as default shipping address</label>
                </div>
            </div>
              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="id_use_default_billing" name="use_default_billing">
                <label class="custom-control-label" for="id_use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3 class="my-2 h3">Payment Option</h3>

              <div class="d-block my-3">
                {% comment %} <div class="custom-control custom-radio">
                  <input id="id_id_payment_option_0_1" name="payment_option" type="radio" class="custom-control-input" value="M" required>
                  <label class="custom-control-label" for="id_id_payment_option_0_1">MOMO PAY</label>
                </div> {% endcomment %}
                
                <div class="custom-control custom-radio">
                  <input id="id_id_payment_option_0_2" value="P" name="payment_option" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="id_id_payment_option_0_2">Paypal</label>
                </div>
              </div>
              
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          {% include "order_snippet.html" %}

          <!-- Promo code -->
          <form class="card p-2" method="POST" action="{% url 'shop:add_coupon' %}">
          {% csrf_token %}
            <div class="input-group">
              {% comment %} <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2"> {% endcomment %}
              {{ couponform.code }}
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}


{% block extra_scripts %}

<script>

const hideShipping = document.querySelector(".hide_shipping_form");
const hideBilling = document.querySelector(".hide_billing_form");
{% comment %} const checkDefaultShipping = document.querySelector("#id_use_default_shipping"); {% endcomment %}
const checkDefaultBilling = document.querySelector("#id_use_default_billing");
const checkSameBilling = document.querySelector("#id_same_shipping_address");

{% comment %} checkDefaultShipping.addEventListener('change', ()=> {
  if(checkDefaultShipping.checked == true){
    hideShipping.style.display = "None";
  } else {
    hideShipping.style.display = "Block";
  }
})  {% endcomment %}

checkSameBilling.addEventListener('change', ()=> {
  if(checkSameBilling.checked == true) {
    hideBilling.style.display = "none";
  } else {
    hideBilling.style.display = "block";
  }
})



</script>




{% endblock extra_scripts %}

templates/home-page.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Lacart Unisex Boutique</strong>
              </h1>

              <p>
                <strong>Best & unique collection of classy fashions</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive and complete Boutique. Loved by over 500 000 users. Men and
                  women clothes
                  available. Get your swag on, stunning fashion.</strong>
              </p>

              <a href="#nav" class="btn btn-outline-white btn-lg">Start
                shopping now
                <i class="fas fa-shopping-cart ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Lacart Unisex Boutique</strong>
              </h1>

              <p>
                <strong>Best & unique collection of classy fashions</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive and complete Boutique. Loved by over 500 000 users. Men and
                  women clothes
                  available. Get your swag on, stunning fashion.</strong>
              </p>

              <a href="#nav" class="btn btn-outline-white btn-lg">Start shopping now
                <i class="fas fa-shopping-cart ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Lacart Unisex Boutique</strong>
              </h1>

              <p>
                <strong>Best & unique collection of classy fashions</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive and complete Boutique. Loved by over 500 000 users. Men and
                  women clothes
                  available. Get your swag on, stunning fashion.</strong>
              </p>

              <a href="#nav" class="btn btn-outline-white btn-lg">start shopping now
                <i class="fas fa-shopping-cart ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav id="nav" class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'shop:item_list' %}">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% for category in cats %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:item_list_by_category' category.slug %}">{{ category }}</a>
                </li>
            {% endfor %}
            

          </ul>
          <!-- Links -->

          <form class="form-inline" action="{% url 'shop:search' %}">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in items %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ item.image.url }}" class="card-img-top"
                  alt="">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.tags.all|join:", " }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item }}
                      {% comment %} <span class="badge badge-pill {{ item.get_label_display }}-color">new</span> {% endcomment %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                    {{ item.discount_price }}
                  {% else %}
                    {{ item.price }}
                  {% endif %}
                  
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% empty %}
          <p>No items yet</p>
          {% endfor %}
          


        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if items.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ items.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page.page_number }}">{{ items.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          
         
          {% if items.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ items.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

templates/item_list.html
{% extends "base.html" %}

{% block content %}

<h2>Here is a list of items</h2>

{% for item in items %}
<p>{{item}}</p>
{% endfor %}


{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">LACART</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">Checkout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/product">Product</a>
          </li> {% endcomment %}
          
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ request.user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'shop:profile_summary' %}">Orders</a>
              <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
              {% comment %} <div class="dropdown-divider"></div> {% endcomment %}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'shop:order_summary' %}">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <i class="fas fa-user"></i>
              <span class="mr-1"> Login </span>
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

templates/request-refund.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

  <!--Main layout-->
  <main class="mt-5">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Request Refund form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 offset-md-2 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card p-4" method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">submit</button>
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

       

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}